/* Standalone/embedded static training module. No paid APIs. */
(() => {
 'use strict';
 const D=window.GD_DATA,C=window.GDCore,app=document.querySelector('#app'),R=window.GD_REGIONAL_AUDIO||{countries:{},recordings:{}};
 if(!document.querySelector('link[href="regional-audio.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="regional-audio.css">');
 const KEY='global-drive.conversation.v4';
 const find=id=>D.questions.find(q=>q.id===id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>Number(n).toFixed(1).replace(/\.0$/,'');
 const responseHints=[
  '先用英语礼貌问候和欢迎客户，再追问一个尚未说明的家庭或用车条件。',
  '先用英语推荐接待背景中的匹配车型并说明相关卖点，再追问一个尚未明确的适配条件。',
  '先用英语认可顾虑并解释可核实的产品价值，再礼貌澄清一个比较或保障问题。',
  '先用英语总结匹配优势和合同、付款、交付步骤，再确认一个尚未明确的成交安排。'
 ];
 let store={recent:[],history:[],active:null},player=null,timer=null,audioEpoch=0,reviewRecord=null;
 function validResult(r){const q=find(r?.questionId),s=r?.score;return !!q&&typeof r.answer==='string'&&r.answer.length<=400&&q.topics.some(t=>t.id===r.topic)&&Array.isArray(r.selection)&&r.selection.every(id=>q.facts.some(f=>f.id===id))&&s&&['known','ask','total'].every(k=>Number.isFinite(s[k])&&s[k]>=0&&s[k]<=100)&&Array.isArray(s.parts)&&s.parts.length===4&&s.parts.every((v,i)=>Number.isFinite(v)&&v>=0&&v<=[10,20,10,10][i])&&Array.isArray(s.notes)&&s.notes.every(v=>typeof v==='string')&&typeof s.reply==='string'&&typeof s.example==='string';}
 try{const data=JSON.parse(localStorage.getItem(KEY)||'null');if(data&&Array.isArray(data.history)&&Array.isArray(data.recent)){
  store.history=data.history.filter(r=>r&&typeof r.id==='string'&&Number.isFinite(r.total)&&r.total>=0&&r.total<=100&&D.scenes[r.scene]&&typeof r.title==='string'&&typeof r.completedAt==='string'&&Array.isArray(r.results)&&r.results.length===2&&r.results.every(validResult)).slice(0,30);
  store.recent=[...new Set(data.recent.filter(id=>find(id)))];
  const a=data.active;if(a&&typeof a.id==='string'&&D.scenes[a.scene]&&Array.isArray(a.draw)&&a.draw.length===2&&a.draw.every(x=>{const q=find(x.id);return q?.scene===a.scene&&Array.isArray(x.factOrder)&&x.factOrder.length===6&&new Set(x.factOrder).size===6&&x.factOrder.every(id=>q.facts.some(f=>f.id===id))&&Array.isArray(x.topicOrder)&&x.topicOrder.length===6&&new Set(x.topicOrder).size===6&&x.topicOrder.every(id=>q.topics.some(t=>t.id===id))})&&[0,1].includes(a.index)&&Array.isArray(a.results)&&a.results.length<=2&&a.results.length>=a.index&&a.results.every((r,i)=>validResult(r)&&r.questionId===a.draw[i].id)&&Array.isArray(a.drafts)&&a.drafts.length===2&&a.drafts.every(x=>x&&Array.isArray(x.selection)&&typeof x.topic==='string'&&typeof x.answer==='string'&&x.answer.length<=400))store.active=a;
 }}catch{}
 const config=window.GDConversationConfig||{};
 if(config.embedded||new URLSearchParams(location.search).get('embed')==='1')document.body.classList.add('embedded');
 function save(){try{localStorage.setItem(KEY,JSON.stringify(store));return true}catch{return false}}
 function usedQuestions(){return [...new Set([...store.recent,...store.history.flatMap(r=>r.results.map(x=>x.questionId)),...(store.active?.draw.map(x=>x.id)||[])])];}
 function route(name){if(location.hash==='#'+name)render();else location.hash=name;}
 function current(){return store.active?find(store.active.draw[store.active.index].id):null}
 function draft(){return store.active.drafts[store.active.index]}
 function cleanup(){audioEpoch++;if(timer){clearInterval(timer);timer=null}if(player){const p=player;player=null;p.pause();p.removeAttribute('src');p.load()}}
 function setText(id,text){const el=document.getElementById(id);if(el)el.textContent=text}
 function top(eyebrow,title,sub=''){return `<div class="intro"><div><div class="eyebrow">${esc(eyebrow)}</div><h1 tabindex="-1">${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div></div>`}
 function customerPortrait(q){const photos={Narin:'narin',Pim:'pim',Anan:'anan',Mali:'mali',Aina:'aina',Budi:'budi',Linh:'linh',Miguel:'miguel'};return `assets/customer-${photos[q.customer.name]||'narin'}.png`}
 function audioInfo(q){const profile=R.countries?.[q.customer.country]||{label:q.customer.countryName+'英语'},record=R.recordings?.[q.id];if(record?.reviewed&&record.src)return {src:record.src,label:profile.label+' · 地域神经语音',regional:true,note:profile.label+'音色 · 已接入'};return {src:q.audio,label:'标准英语备用音频',regional:false,note:profile.label+'音频待补充'};}
 function regionalCount(){return D.questions.filter(q=>audioInfo(q).regional).length;}
 function list(){app.innerHTML=top('MODULE 02 · 交流互动','交流互动台')+
 (store.active?`<div class="resume"><div><strong>你有一轮未完成的练习</strong><p>${D.scenes[store.active.scene].title} · 第 ${store.active.index+1}/2 题</p></div><button class="btn" data-action="resume">继续练习 →</button></div>`:'')+
 `<section class="card scene-library"><div class="eyebrow">CONVERSATION SCENARIOS</div><h2>选择练习场景</h2><div class="scene-grid">${D.scenes.map((s,i)=>{const active=store.active?.scene===i,left=C.remaining(D.questions,i,usedQuestions()),action=active?'resume':'start';return `<button class="scene-tile" data-action="${action}" data-scene="${i}" ${!active&&!left?'disabled':''}><div class="tile-code">0${i+1}<img class="scene-logo" src="assets/scene-${i+1}.svg" alt="" width="52" height="52"></div><h3>${s.title}</h3><div class="tile-link"><span>${active?'继续练习':left?'开始练习':'该场景题目已全部练习'}</span><span>${left||active?'→':''}</span></div></button>`}).join('')}</div></section>`;}
 function start(scene){if(!D.scenes[scene])return;
  if(!C.remaining(D.questions,scene,usedQuestions())){route('scenes');return}const draw=C.draw(D.questions,scene,usedQuestions());store.recent=[...new Set([...store.recent,...draw.map(x=>x.id)])];
  store.active={id:typeof crypto.randomUUID==='function'?crypto.randomUUID():Date.now()+'-'+Math.random(),scene,draw,index:0,results:[],drafts:[0,1].map(()=>({selection:[],topic:'',answer:'',choice:'',assisted:false})),startedAt:new Date().toISOString()};save();route('practice');}
 function exercise(){const a=store.active;if(!a){route('scenes');return}const q=current(),s=D.scenes[a.scene],d=draft(),locked=!!a.results[a.index],draw=a.draw[a.index];
  app.innerHTML=`<button class="link" data-action="scenes">← 返回场景列表</button>${top(`SCENARIO 0${a.scene+1} · ${s.en}`,s.title)}<div class="exercise-meta"><div class="steps" role="group" aria-label="题目切换"><button class="step ${a.index===0?'on':''}" data-action="question" data-index="0" aria-label="第 1 题" ${a.index===0?'aria-current="step"':''}>1</button><span aria-hidden="true">—</span><button class="step ${a.index===1?'on':''}" data-action="question" data-index="1" aria-label="第 2 题" ${a.index===1?'aria-current="step"':''} ${!a.results[0]?'disabled title="完成第 1 题后可切换"':''}>2</button><span>第 ${a.index+1} / 2 题</span></div></div><div class="task"><strong>本题任务</strong> · ${s.task}<details><summary>查看接待背景</summary><p>${esc(q.context)}</p></details></div><div class="grid"><section class="card customer"><div class="avatar customer-portrait"><img src="${customerPortrait(q)}" alt="${esc(q.customer.countryName)}客户头像" loading="eager"></div><div><div class="eyebrow">${q.customer.country} · ${q.customer.countryName}</div><h2>${esc(q.customer.name)} · ${esc(q.customer.city)}</h2><p>请从客户语音中发现具体需求。</p><span class="small">国籍仅为情景背景，不代表声音口音</span></div></section><section class="card audio"><div class="audio-head"><button class="play" id="play" data-action="play" aria-label="播放客户语音">▶</button><div><div class="eyebrow">CLIENT INQUIRY · LISTEN FIRST</div><h2>听音取证</h2><p id="audioStatus" aria-live="polite">点击播放，可暂停与重复收听</p></div><div class="wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><input class="audio-track" id="audioProgress" type="range" min="0" max="100" step="0.1" value="0" aria-label="客户语音播放进度" disabled><div class="audio-times"><span id="audioElapsed">00:00</span><span class="countdown" id="countdown" role="timer"></span><span id="audioDuration">加载中</span></div><div class="audio-tools"><label class="small">语速 <select id="speed" aria-label="播放速度"><option value="1">正常</option><option value="0.8">0.8 倍</option></select></label><span class="small">本地标准英语音频</span></div><div id="audioFallback" hidden><button class="link" data-action="transcript">无法播放？使用文字辅助</button></div></section></div>
  <div class="work" id="answerArea"><section class="card"><div class="eyebrow">I KNOW · CHECK AFTER LISTENING</div><h2>已确认信息 <span class="small">多选 · 50 分</span></h2><p class="sub">只勾选客户明确说过的信息，不作额外推测。</p><fieldset ${locked?'disabled':''} class="options" aria-label="已确认信息">${draw.factOrder.map(id=>q.facts.find(f=>f.id===id)).filter(Boolean).map(f=>factOption(f,d,locked)).join('')}</fieldset><p class="small">每个正确项均分；误选扣同等分值，最低 0 分。</p></section><section class="card"><div class="eyebrow">I NEED TO ASK · CHOOSE ONE TOPIC</div><h2>待追问信息 <span class="small">单选 · 50 分</span></h2><p class="sub">选择一个尚需明确的主题，再用英语具体追问。</p><fieldset class="options topics" aria-label="待追问信息" ${locked?'disabled':''}>${draw.topicOrder.map(id=>q.topics.find(t=>t.id===id)).filter(Boolean).map(t=>topicOption(t,d,locked)).join('')}</fieldset><label class="inputlabel" for="answer"><span>MY QUESTION TO THE CLIENT</span><span id="charCount">${d.answer.length} / 400</span></label><textarea id="answer" maxlength="400" ${locked?'disabled':''} placeholder="例如，用一个礼貌而具体的问题了解客户尚未说明的信息。">${esc(d.answer)}</textarea><div class="actions">${locked?'':`<button class="btn" data-action="submit">提交问题，获取客户回复 →</button>`}</div><p class="error" id="error" role="alert"></p><div id="feedback" aria-live="polite">${locked?feedback(a.results[a.index],q):''}</div></section></div>${d.assisted&&!locked?transcript(q):''}`;
  const ai=audioInfo(q),customerNote=document.querySelector('.customer .small'),audioLabel=document.querySelector('.audio-tools .small:last-child');
  customerNote?.remove();audioLabel?.remove();document.querySelector('.exercise-meta [data-action="rules"]')?.remove();
  document.querySelector('.task details')?.setAttribute('open','');document.querySelector('#answerArea .card > .options + .small')?.remove();
  const answer=document.querySelector('#answer');if(answer)answer.placeholder=responseHints[a.scene];
  if(a.scene<2)document.querySelector('.work')?.insertAdjacentHTML('beforebegin',stageChoice(q,d,locked));
  setupAudio(q,ai);

 }
 function transcript(q){return `<details open class="review card"><summary>听力原文与中文翻译</summary><p lang="en">${esc(q.script)}</p><p class="translation"><strong>中文：</strong>${esc(q.translation||'')}</p></details>`}
 function stageChoice(q,d,locked){const persona=q.scene===0,choices=persona?['务实家庭型','科技先锋型','商务精英型']:['Family E','Smart E','Comfort E'],correct=persona?q.persona:q.recommendedModel;return `<section class="card stage-choice"><div class="eyebrow">${persona?'CUSTOMER PROFILE':'MODEL MATCH'}</div><h2>${persona?'判断客户画像':'选择推荐车型'}</h2><p class="sub">${persona?'结合听到的用途和偏好选择一类。':'根据接待背景中的客户画像选择匹配的教学模拟车型。'}</p><fieldset ${locked?'disabled':''} aria-label="${persona?'客户画像':'推荐车型'}">${choices.map(value=>`<label class="stage-choice-option"><input type="radio" name="stageChoice" value="${esc(value)}" ${d.choice===value?'checked':''}><span>${esc(value)}</span>${locked?`<strong class="${value===correct?'right':'wrong'}">${value===correct?'✓ 匹配':'不匹配'}</strong>`:''}</label>`).join('')}</fieldset></section>`}
 function factOption(f,d,locked){const selected=d.selection.includes(f.id),right=f.correct===selected;return `<div class="option-review ${locked?(right?'review-correct':'review-wrong'):''}"><label class="option"><input type="checkbox" name="fact" value="${f.id}" ${selected?'checked':''} ${locked?'aria-describedby="'+f.id+'-analysis"':''}><span class="fact-text">${esc(f.text)}</span>${locked?`<strong class="fact-status">${f.correct?(selected?'✓ 选对 · 应选择':'! 漏选 · 应选择'):(selected?'× 误选 · 不应选择':'✓ 排除 · 不应选择')}</strong>`:''}</label>${locked?`<div class="inline-analysis" id="${f.id}-analysis"><p>解析：${esc(f.evidence)}</p></div>`:''}</div>`}
 function topicOption(t,d){return `<div class="option-review"><label class="option topic"><input type="radio" name="topic" value="${t.id}" ${d.topic===t.id?'checked':''}><span>${esc(t.label)}</span></label></div>`}
 function feedback(r,q){const action=store.active?.index===0?'<div class="actions"><button class="btn" data-action="question" data-index="1">下一题 →</button></div>':'<div class="actions"><button class="btn" data-action="next">查看场景成绩 →</button></div>',ai=r.score.source==='xfyun';return `<section class="card feedback-card"><div class="response-topline"><div class="eyebrow">${ai?'AI CLIENT RESPONSE · 讯飞客户回复':'CLIENT RESPONSE · 本地备用回复'}</div><div class="compact-score"><span>${ai?'AI 综合评分':'本地参考分'} <b>${fmt(r.score.total)}</b>/100</span><span>已确认 ${fmt(r.score.known)}/50 · 追问 ${r.score.ask}/50${r.assisted?' · 文字辅助':''}</span></div></div><div class="feedback"><strong>${esc(q.customer.name)}</strong><p lang="en">“${esc(r.score.reply)}”</p></div><ul class="feedback-notes">${r.score.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><details open class="review"><summary>查看完整听力原文与中文翻译</summary><p lang="en">${esc(q.script)}</p><p class="translation"><strong>中文：</strong>${esc(q.translation||'')}</p></details>${action}</section>`}
 function capture(){if(!store.active||store.active.results[store.active.index])return;const d=draft();d.answer=document.querySelector('#answer')?.value??d.answer;d.selection=[...document.querySelectorAll('[name="fact"]:checked')].map(x=>x.value);d.topic=document.querySelector('[name="topic"]:checked')?.value||'';d.choice=document.querySelector('[name="stageChoice"]:checked')?.value||'';save();}
 async function requestAiConversation(q,d){const topic=q.topics.find(item=>item.id===d.topic),heard=d.selection.map(id=>q.facts.find(item=>item.id===id)?.text).filter(Boolean),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);try{const response=await fetch('../api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({mode:'conversation',country:q.customer.countryName,scenarioTitle:D.scenes[q.scene].title,clientName:q.customer.name,city:q.customer.city,context:q.context,caseText:q.script,heard,topicLabel:topic?.label||'',topicStatus:topic?.status||'',clientFacts:q.replyBank,question:d.answer.trim()})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'AI 服务暂时不可用');return data}finally{clearTimeout(timeout)}}
 function mergeAiScore(local,result){const ask=Math.round(Number(result.questionScore)*5)/10;return {...local,ask,total:Math.round((local.known+ask)*10)/10,notes:[`讯飞追问评分：${result.questionScore}/100（相关性 ${result.relevanceScore}、清晰度 ${result.clarityScore}、礼貌性 ${result.politenessScore}、具体性 ${result.specificityScore}）。`,...result.advice],reply:result.clientReply,example:result.sampleQuestion,source:'xfyun',aiDimensions:{relevance:result.relevanceScore,clarity:result.clarityScore,politeness:result.politenessScore,specificity:result.specificityScore}}}
 async function submit(){if(!store.active||store.active.results[store.active.index])return;capture();const d=draft(),q=current();if(!d.topic||!d.answer.trim()){setText('error','请选择一个追问主题，并输入英语问题。');return}if(q.scene<2&&!d.choice){setText('error',q.scene===0?'请先判断客户画像。':'请先选择推荐车型。');return}
  const button=document.querySelector('[data-action="submit"]');if(button){button.disabled=true;button.textContent='讯飞 AI 正在分析…'}let score=C.score(q,d.selection,d.topic,d.answer);try{score=mergeAiScore(score,await requestAiConversation(q,d))}catch(error){score={...score,source:'local-fallback',notes:[`讯飞 AI 暂未连接，已使用本地规则评分。${location.hostname==='127.0.0.1'||location.hostname==='localhost'?'发布到 EdgeOne 后可调用已配置的讯飞接口。':'请稍后重试。'}`,...score.notes]}}store.active.results[store.active.index]={questionId:q.id,selection:[...d.selection],topic:d.topic,answer:d.answer.trim(),choice:d.choice,assisted:d.assisted,score};save();render();document.querySelector('#feedback')?.scrollIntoView({behavior:'smooth',block:'start'});
 }
 function finish(){const a=store.active;if(!a||a.results.length!==2)return;const total=Math.round(a.results.reduce((sum,r)=>sum+r.score.total,0)/2);const record={id:a.id,scene:a.scene,startedAt:a.startedAt,completedAt:new Date().toISOString(),total,title:C.title(D.scenes[a.scene],total),results:a.results,ruleVersion:2};store.history=[record,...store.history.filter(r=>r.id!==record.id)].slice(0,30);store.active=null;save();reviewRecord=record;window.dispatchEvent(new CustomEvent('gd:conversation-complete',{detail:JSON.parse(JSON.stringify(record))}));if(typeof config.onComplete==='function'){try{config.onComplete(JSON.parse(JSON.stringify(record)))}catch(err){console.error('Host completion callback failed',err)}}route('results');}
 function result(){const r=reviewRecord||store.history[0];if(!r){route('scenes');return}reviewRecord=r;const s=D.scenes[r.scene],hasAi=r.results.some(x=>x.score.source==='xfyun');app.innerHTML=`<button class="link" data-action="scenes">← 返回场景列表</button><section class="card result"><div class="eyebrow">PRACTICE COMPLETE · 练习已完成</div><div class="medal" aria-hidden="true">✧</div><h2>${s.title}</h2><p>每一次认真倾听，都是有效沟通的开始。</p><div class="score">${r.total}<small> / 100</small></div><div class="rank">${esc(r.title)}</div><p class="small">两题平均 · ${hasAi?'讯飞 AI 与听辨综合评分':'本地规则参考分'}${r.results.some(x=>x.assisted)?' · 含文字辅助':''}</p><div class="resultgrid">${r.results.map((x,i)=>{const q=find(x.questionId);return `<article class="card"><div class="eyebrow">QUESTION 0${i+1} · ${esc(q.customer.name)} / ${q.customer.countryName}</div><h2>${fmt(x.score.total)} <span class="small">/ 100</span></h2><p>听辨确认 ${fmt(x.score.known)}/50 · 英语追问 ${x.score.ask}/50</p><div class="bar"><span style="width:${Math.max(0,Math.min(100,x.score.total))}%"></span></div><details class="review"><summary>作答、评分与听力证据</summary><p lang="en">${esc(x.answer)}</p><ul>${x.score.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><p>参考：${esc(x.score.example)}</p><p>客户：${esc(x.score.reply)}</p><p>原文：${esc(q.script)}</p><div class="evidence">${q.facts.map(f=>`<p>${f.correct?'应选':'不应选'}${x.selection.includes(f.id)?' · 已选':' · 未选'}：${esc(f.text)}<br>${esc(f.evidence)}</p>`).join('')}</div></details></article>`}).join('')}</div><div class="tip">${r.total>=80?'继续保持：追问应针对尚未明确的信息，避免只重复客户已经说过的内容。':'改进方向：先区分事实与推测，再用完整问句澄清一个关键信息。可以展开分项查看具体建议。'}</div><div class="actions" style="justify-content:center"><button class="btn" data-action="start" data-scene="${r.scene}" ${C.remaining(D.questions,r.scene,usedQuestions())?'':'disabled'}>${C.remaining(D.questions,r.scene,usedQuestions())?'再练一轮':'该场景题目已全部练习'}</button><button class="link" data-action="scenes">返回场景列表</button></div></section>`;}
 function rules(){const dialog=document.querySelector('#rulesDialog');dialog.showModal();}
 function time(t){t=Math.max(0,Math.floor(t||0));return String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0')}
 function setupAudio(q,info=audioInfo(q)){const epoch=++audioEpoch,p=new Audio(info.src);player=p;p.preload='metadata';const active=()=>player===p&&epoch===audioEpoch;
  const update=()=>{if(!active())return;const duration=Number.isFinite(p.duration)?p.duration:0,left=(duration-p.currentTime)/p.playbackRate,progress=document.querySelector('#audioProgress');if(!progress)return;progress.disabled=!duration;progress.value=duration?p.currentTime/duration*100:0;progress.setAttribute('aria-valuetext',time(p.currentTime)+' / '+time(duration));setText('audioElapsed',time(p.currentTime));setText('audioDuration',duration?time(duration):'加载中');setText('countdown',duration&&!p.ended&&left>0&&left<=5?`剩余 ${Math.ceil(left)} 秒${p.paused?' · 已暂停':''}`:'');setText('play',p.paused?'▶':'Ⅱ');document.querySelector('#play')?.setAttribute('aria-label',p.paused?'播放客户语音':'暂停客户语音');};
  ['loadedmetadata','durationchange','timeupdate','pause','play','seeked','ratechange'].forEach(event=>p.addEventListener(event,update));p.addEventListener('ended',()=>{if(active()){update();setText('audioStatus','播放完毕，点击可重听')}});p.addEventListener('error',()=>{if(active()){setText('audioStatus','音频暂时无法加载，可重试或使用文字辅助');setText('audioDuration','不可用');document.querySelector('#audioFallback').hidden=false;setText('countdown','')}});timer=setInterval(update,150);
 }
 async function play(){const p=player;if(!p)return;if(!p.paused){p.pause();setText('audioStatus','已暂停，点击继续');return}try{if(p.error)p.load();if(p.ended)p.currentTime=0;await p.play();if(player===p)setText('audioStatus','正在播放客户需求…')}catch{if(player===p){setText('audioStatus','无法播放，请点击重试或使用文字辅助');document.querySelector('#audioFallback').hidden=false}}}
 function decorateList(){document.querySelector('.resume')?.remove();document.querySelectorAll('.content > .notice,.scene-library > .notice,.scene-tile .tile-detail').forEach(el=>el.remove());document.querySelector('.scene-library + .actions')?.remove()}
 function decorateResult(){const r=reviewRecord||store.history[0];if(!r)return;document.querySelectorAll('.resultgrid article details').forEach((details,i)=>{const item=r.results[i],q=find(item?.questionId);if(!q)return;if(q.scene<2&&item.choice){const p=document.createElement('p');const answer=q.scene===0?q.persona:q.recommendedModel;p.textContent=`${q.scene===0?'客户画像':'推荐车型'}：${item.choice}；参考匹配：${answer}`;details.querySelector('.evidence')?.before(p)}if(q.translation){const p=document.createElement('p');p.className='translation';p.innerHTML='<strong>中文：</strong>'+esc(q.translation);details.querySelector('.evidence')?.before(p)}})}
 function render(){cleanup();document.querySelector('.top .pill')?.remove();document.querySelector('.sidefoot')?.remove();document.querySelector('.footer')?.remove();const page=location.hash.slice(1);document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.action==='scenes'));if(page==='practice')exercise();else if(page==='results'){result();decorateResult()}else{list();decorateList()}window.scrollTo(0,0);}
 document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;
  if(action==='start')start(Number(b.dataset.scene));else if(action==='scenes')route('scenes');else if(action==='resume')route('practice');else if(action==='rules')rules();else if(action==='play')play();else if(action==='submit')submit();else if(action==='question'){const target=Number(b.dataset.index);if(store.active&&[0,1].includes(target)&&target!==store.active.index&&(target===0||store.active.results[0])){capture();store.active.index=target;save();render()}}else if(action==='next'){if(store.active?.index===1&&store.active.results[1])finish()}
  else if(action==='transcript'){draft().assisted=true;save();render()}
 });
 document.addEventListener('input',event=>{if(event.target.id==='answer'){setText('charCount',event.target.value.length+' / 400');capture()}else if(event.target.id==='audioProgress'&&player&&Number.isFinite(player.duration)){player.currentTime=player.duration*Number(event.target.value)/100}else if(['fact','topic','stageChoice'].includes(event.target.name))capture();});
 document.addEventListener('change',event=>{if(event.target.id==='speed'&&player)player.playbackRate=Number(event.target.value);});
 window.addEventListener('hashchange',render);window.addEventListener('pagehide',cleanup);render();
})();
